### ISSUE TITLE
Safari support...

### ISSUE THREAD

**Issue by glomotion** [wtfil/image-set-polyfill#2]
Hey there man.

Firstly, thanks for the cool pollyfill for what is probably a pretty volatile css4 feature. :)

Just wondering: atm ur pollyfill does not seem to bring image-set functionality to Safari - are there by any chance, plans to rectify this in the nearby future? If not, perhaps I could have a go, and submit to you as  a PR...

An example to test in safari: http://codepen.io/glomotion/pen/rVwNRm?editors=101

**Comment by wtfil** [comment]
Hi there!
Have not tested on Safari, but it easy to fix)
I have to reach my pc in a few hours to do this, so today I let you know:)

**Comment by wtfil** [comment]
@glomotion hm. Just tried in Safari and mobile Safari and both work good (even with your example).
What Safari are you using?

**Comment by glomotion** [comment]
Safari Version 8.0.6 (10600.6.3)

Oh how bizarre. I think you're right... http://codepen.io/glomotion/pen/rVwNRm <-- is working fine for me after swapping the images to something else. Perhaps I safari had some weird permission problems with those drive images...

Thanks for your help @wtfil ! :)
