### ISSUE TITLE
Polyfill image selection logic might be broken in FF?

### ISSUE THREAD

**Issue by glomotion** [wtfil/image-set-polyfill#3]
I've amended the test pen to demonstrate what appears to be an image selection issue in the polyfill logic for Firefox (OSX 38.0.5) ...

http://codepen.io/glomotion/pen/rVwNRm

In this case, the polyfill should be choosing the 1x image (the current screen is 1x density), though it seems to be choosing the 3x image instead. 

![screen shot 2015-06-16 at 10 03 25 am](https://cloud.githubusercontent.com/assets/1452237/8173322/f14475f0-140e-11e5-85ef-e0c313fd7bc0.png)

**Comment by wtfil** [comment]
fixed with 8a28fd6eb87ca30349b5f8a0e5f586a358276ee2
