### ISSUE TITLE
A way to trigger the polyfill to run, after loading in content via ajax / DOM mutation

### ISSUE THREAD

**Issue by glomotion** [wtfil/image-set-polyfill#4]
The very first project I was hoping on using this polyfill in is an Angular project, which loads content in via a $http request, then builds out the DOM using ng-repeats. It appears that this polyfill is designed to automatically kick in once only at "DOMContentLoaded" - or am I misreading your code? 

Basically, "DOMContentLoaded" is not the only time that I need the polyfill to do it's thing - so having a .run()/start() function available externally would probably be ideal.

Are you planning on adding this functionality at all, or would you consider a PR to this effect?

**Comment by wtfil** [comment]
Hi! DOMContentLoaded is not perfect solution and I was thinking to replace it with `MutationObserver` which works faster and will fulfill your requirements.
I will fix it today-tomorrow:)

**Comment by glomotion** [comment]
Nice! That feature should be all i need to get the polyfill working in this current instance, I'll flick you a link to it once it's public. :-)

**Comment by wtfil** [comment]
Hi @glomotion 
I've switched to `MutationObserver` but I am not 100% sure it works with angular. I am not familiar with angular, so can you try `image-set-polyfill@0.1.4` with your project and give the feedback.
I it will not work, I will move forward:)

**Comment by glomotion** [comment]
Hey again Evgen! 

MutationObserver should be fine! After updating your pollyfill is now kicking in as objects are added and removed from the page using angular/ng-repeat! 

Win! :)

**Comment by wtfil** [comment]
@glomotion Nice to hear it! :)
